### ISSUE TITLE
Bugfix: Apply scaling calculation to keypress detection

### ISSUE THREAD

**Issue by nixuser1980** [xavierbasc/dmos#5]
Branch SDL_button_press_registering implemented keypress detection, but without considering scaling (for simplicity). A bugfix branch will be created to implement this feature fully.

**Comment by xavierbasc** [comment]
ok ;-)

**Comment by nixuser1980** [comment]
FYI: accidentally committed e87966af8d8cf977030334c285bd54fccac20fd5
directly to main. Merged main into the correct branch:
bugfix_SDL_button_press_registration_with_scaling and continued.

Sorry for any inconvenience.

**Comment by nixuser1980** [comment]
Bug fixed in: e615f41a1bff372cd776d8239d604d3390925776.
Will merge to main branch.

**Comment by nixuser1980** [comment]
Merged to main; closing.

**Comment by xavierbasc** [comment]
No worries, my friend. I think I’m working poorly with the main branch and
merging things I shouldn’t. I’m not used to having the STM32 branch out of
sync. Besides, I’ll need to do something to work with the DMOS core from
STM32 to start integrating it into the development and begin working on the
core. It’s a bit of a mess. Don’t worry; this is meant to be fun. I’m the
first one to make mistakes.
